services:
  app:
    build: .
    tty: true
    command: sh -lc "npm install && npx prisma generate && until npx prisma db push; do sleep 2; done && node index.js"
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:16.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nn_chat
      TZ: "Asia/Tokyo"
    volumes:
      - ../nn-chat-db:/var/lib/postgresql/data

volumes:
  node_modules:
